spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    show_sql: true
    hibernate:
      ddl-auto: validate

  h2:
    console:
      enabled: true

  liquibase:
    enabled: true

  output:
    ansi:
      enabled: always